name: Docker Image CI

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true
      - uses: nelonoel/branch-name@v1.0.1
      - name: Publish Image
        uses: whoan/docker-build-with-cache-action@v5
        with:
          username: oliver-ni
          password: ${{ secrets.GHCR_PAT }}
          registry: ghcr.io
          image_name: p2-priv
          image_tag: latest,${{ github.sha }}
